public enum Specialty {
    ANESTHESIOLOGY, ANATOMY, CARDIOLOGY, SURGERY, PEDIATRICS,
    DERMATOLOGY, GASTRENTEROLOGY, HEMATOLOGY, REHABILITATION_MEDICINE,
    OPTHALMOLOGY,
    NUTRITION, ORTHOPEDICS
}
